version: '3.7'
services:
  web:
    build: .
    command: bash script/run_web.sh
    restart: on-failure
    env_file:
      - ./.env
    expose:
      - '8000'
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${RDS_USERNAME}
      - POSTGRES_PASSWORD=${RDS_PASSWORD}
      - POSTGRES_DB=${RDS_DB_NAME}
    ports:
      - ${RDS_PORT}:5434
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
